### ISSUE TITLE
Resizer doubles movement

### ISSUE THREAD

**Issue by mjschurig** [nmingaleev/react-draggable-resizable-panel#1]
I encountered an issue with the resizer component. I use Windows 10 with Chrome Canary. My Windows display settings are set to 4k with the recommended scaling factor of 300%. This leads to three times more resizing as the mouse movements sugests. This issue can be fixed by replacing lines 11 to 15 in the resizer index.js with the following:

const ratio = window.devicePixelRatio
const handleMouseMove = (e) => {
       if (!direction) return
       onResize(direction, e.movementX/ratio, e.movementY/ratio)
}

This scales the movement by the display scaling factor, leading to the correct resizing operation.

Confer to: https://github.com/w3c/pointerevents/issues/602

**Comment by nmingaleev** [comment]
That's a great point! I didn't know about it. Could please submit a pull request?

**Comment by mjschurig** [comment]
Done
